# Generated by Django 4.0.5 on 2023-05-16 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('capacidad', models.CharField(max_length=2)),
                ('numerobus', models.CharField(max_length=2)),
                ('tipo', models.CharField(choices=[('Escolar', 'Escolar'), ('Publico', 'Publico')], default='F', max_length=7, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='F', max_length=9, verbose_name='Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cantidad', models.IntegerField()),
                ('fecha_viaje', models.DateTimeField(auto_now_add=True)),
                ('efectivo', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Azure.bus')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Azure.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.CharField(max_length=3)),
                ('codigo', models.CharField(max_length=6)),
                ('idPasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Azure.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='SimularAccesoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=7)),
                ('fecha_viaje', models.DateTimeField(auto_now_add=True)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Azure.tarjeta')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Azure.viaje')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='idTarjeta',
            field=models.ManyToManyField(through='Azure.Viaje', to='Azure.pasajero'),
        ),
    ]
